#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

httpd -f $OPENSHIFT_HOMEDIR/app-root/data/conf/httpd.conf
