#!/bin/bash

APACHE_CONF=${OPENSHIFT_HOMEDIR}/app-root/data/conf/http.conf

if [ -f ${APACHE_CONF} ]; then
    httpd -f $OPENSHIFT_HOMEDIR/app-root/data/conf/httpd.conf -k stop
    exit 0
fi

source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
if [ -z "$(ps -ef | grep testrubyserver.rb | grep -v grep)" ]
then
    client_result "Application is already stopped"
else
    kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
