language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
#install: "pip install pelican Markdown --use-mirrors"
# command to run tests

# travis-ci always cd into our project root after checking out the source
script: PYTHONPATH=./packages.zip nosetests -s
